export const dumbData = [
  {
    id: "54g21dsdff4g5h6",
    date_saved: 1719447810,
    company: "InnovateTech",
    position: "Software Engineer",
    description: "Full stack developer",
    location: "Berlin, Germany",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386610,
    stage: 5,
  },
  {
    id: "67h32kfdbi9l8m7",
    date_saved: 1719447815,
    company: "CyberNet",
    position: "Data Analyst",
    description: "Full stack developer",
    location: "Amsterdam, Netherlands",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386615,
    stage: 3,
  },
  {
    id: "78j43lm2qwen3o8",
    date_saved: 1719447820,
    company: "QuantumSoft",
    position: "Back-end Dev",
    description: "Full stack developer",
    location: "Paris, France",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386620,
    stage: 4,
  },
  {
    id: "89k54no5pqwe6q9",
    date_saved: 1719447825,
    company: "FinTech Group",
    position: "DevOps Engineer",
    description: "Full stack developer",
    location: "Zurich, Switzerland",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386625,
    stage: 5,
  },
  {
    id: "90l65op8qweq7r0",
    date_saved: 1719447830,
    company: "NextGen Solutions",
    position: "UI/UX Designer",
    description: "Full stack developer",
    location: "Stockholm, Sweden",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386630,
    stage: 4,
  },
  {
    id: "12a23bcasdd5e6",
    date_saved: 1719447835,
    company: "AlphaTech",
    position: "Machine Learning Engineer",
    description: "Full stack developer",
    location: "London, UK",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386635,
    stage: 4,
  },
  {
    id: "23b34cd5asde6f7",
    date_saved: 1719447840,
    company: "GreenEnergy",
    position: "Sustainability Analyst",
    description: "Full stack developer",
    location: "Oslo, Norway",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386640,
    stage: 5,
  },
  {
    id: "34c45de6fasd7g8",
    date_saved: 1719447845,
    company: "HealthTech",
    position: "Full Stack Developer",
    description: "Full stack developer",
    location: "Madrid, Spain",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386645,
    stage: 3,
  },
  {
    id: "45d56ef7asd8h9",
    date_saved: 1719447850,
    company: "EduSoft",
    position: "Data Scientist",
    description: "Full stack developer",
    location: "Vienna, Austria",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386650,
    stage: 4,
  },
  {
    id: "56e67fgasdh9i0",
    date_saved: 1719447855,
    company: "AgroTech",
    position: "Blockchain Developer",
    description: "Full stack developer",
    location: "Helsinki, Finland",
    status: "",
    url: "https://www.innovatetech.com",
    date_applied: 1719386655,
    stage: 5,
  },
];
